---
# tasks file for kubecontrolplane

- name: Run the equivalent of "yum update" as a separate step
  yum:
    name: "*"
    state: latest

- name: Install utils
  yum:
    name: "{{ item }}"
    state: present
  loop:
    - yum-utils
    - curl
    - wget
    - device-mapper-persistent-data
    - lvm2

- name: Enable EPEL repository (Extra Packages for Enterprise Linux)
  shell: "amazon-linux-extras install epel -y && touch /var/tmp/epel_installed"
  args:
    creates: /var/tmp/epel_installed
  become: true

- include_tasks: install_docker_kubernetes.yml