---
# tasks file for kubecontrolplane

- name: Run the equivalent of "yum update" as a separate step
  yum:
    name: "*"
    state: latest

- name: Install utils (excluding curl)
  yum:
    name: "{{ item }}"
    state: present
  loop:
    - yum-utils
    - wget
    - device-mapper-persistent-data
    - lvm2

- name: Check if curl-minimal is installed
  shell: "rpm -q curl-minimal"
  register: curl_minimal_installed
  ignore_errors: yes

- name: Debug curl_minimal_installed
  debug:
    var: curl_minimal_installed

- name: Remove curl-minimal if installed
  yum:
    name: curl-minimal
    state: absent
  when: curl_minimal_installed.rc == 0

- name: Install curl if curl-minimal was removed
  yum:
    name: curl
    state: present
  when: curl_minimal_installed.rc == 0

- name: Enable EPEL repository (Extra Packages for Enterprise Linux)
  command: "dnf install -y epel-release"
  args:
    creates: /var/tmp/epel_installed
  register: epel_installed
  changed_when: "'Complete!' in epel_installed.stdout"
  ignore_errors: yes

- name: Debug epel_installed
  debug:
    var: epel_installed

- include_tasks: install_docker_kubernetes.yml