---
- hosts: kubectrl
  become: yes
  tasks:
    - name: Get kubeadm token join command and save it to a file on the control plane
      shell: kubeadm token create --print-join-command > /tmp/token_cmd.sh