---
- hosts: localhost
  gather_facts: no
  tasks:
    - name: Upload the join command to S3
      aws_s3:
        aws_access_key: "{{ lookup('env', 'AWS_ACCESS_KEY_ID') }}"
        aws_secret_key: "{{ lookup('env', 'AWS_SECRET_ACCESS_KEY') }}"
        region: "{{ lookup('env', 'AWS_DEFAULT_REGION') }}"
        bucket: "{{ lookup('env', 'ANSIBLE_BUCKET_NAME') }}"
        mode: put
        object: "token_cmd.sh"
        src: "{{ playbook_dir }}/token_cmd.sh"