- hosts: jenkins
  become: true
  tasks:
    - name: Update the apt package manager
      apt:
        update_cache: yes

    - name: Install dependencies
      apt:
        name:
          - curl
          - unzip
        state: present

    - name: Install AWS CLI v2
      shell: |
        curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
        unzip awscliv2.zip
        sudo ./aws/install

    - name: Verify AWS CLI installation
      shell: aws --version
      register: aws_cli_version

    - name: Display AWS CLI version
      debug:
        msg: "AWS CLI version: {{ aws_cli_version.stdout }}"
