---
- hosts: jenkins
  become: true
  tasks:
    - name: Install Amazon Corretto 11
      yum:
        name: java-11-amazon-corretto
        state: present

    - name: Add Jenkins repo
      yum_repository:
        name: jenkins
        description: Jenkins
        baseurl: http://pkg.jenkins.io/redhat-stable/
        gpgcheck: yes
        gpgkey: http://pkg.jenkins.io/redhat-stable/jenkins.io.key

    - name: Install Jenkins
      yum:
        name: jenkins
        state: present

    - name: Start Jenkins service
      service:
        name: jenkins
        state: started
        enabled: yes

    - name: Install yum-utils
      yum:
        name: yum-utils
        state: present

    - name: Add HashiCorp GPG key
      rpm_key:
        state: present
        key: https://rpm.releases.hashicorp.com/gpg

    - name: Add HashiCorp repository for Amazon Linux 2
      yum_repository:
        name: hashicorp
        description: HashiCorp Stable - $basearch
        baseurl: https://rpm.releases.hashicorp.com/AmazonLinux/2/x86_64/stable
        gpgcheck: yes
        gpgkey: https://rpm.releases.hashicorp.com/gpg
        enabled: yes

    - name: Update yum repository metadata
      command: yum makecache

    - name: Install Terraform
      yum:
        name: terraform
        state: present
      register: terraform_install_result
      failed_when: "'No package terraform available.' in terraform_install_result.msg"

    - name: Install Ansible
      yum:
        name: ansible
        state: present

    - name: Install pip
      yum:
        name: python3-pip
        state: present

    - name: Install boto3 and botocore
      pip:
        name: 
          - boto3
          - botocore
        state: present

    - name: Install amazon.aws collection
      command: >
        ansible-galaxy collection install amazon.aws
      environment:
        PATH: "/usr/local/bin:/usr/bin:/usr/local/sbin:/usr/sbin:/home/jenkins/.local/bin:/home/jenkins/bin"

    - name: Ensure jenkins user can sudo without password
      lineinfile:
        path: /etc/sudoers
        state: present
        line: 'jenkins ALL=(ALL) NOPASSWD: ALL'
        validate: 'visudo -cf %s'